# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CoV Index
description: > # this means to ignore newlines until next variable
  CoV Index is the map of Coronavirus Science.
license: "cc 2020 Ian Dennis Miller"

# Links
baseurl: "/covid-web" # the subpath of your site, e.g. /blog
url: "https://iandennismiller.github.io" # the base hostname & protocol for your site
permalink: none

# include/exclude files
include: ["_pages", "_root", "_js"]
exclude: ["docs", "Readme.md", "Todo.md", "Makefile", "vendor", "Gemfile", "Gemfile.lock"]

# Build settings
markdown: kramdown

# sass:
#   style: compressed

gems:
  - jekyll-sitemap
  - jekyll-datapage-generator

# Email
# email: iandennismiller@gmail.com

# Twitter
# twitter_username: iandennismiller

# GitHub
# github_username: iandennismiller

# Google Analytics
# google_analytics_id: 

# Disqus comments
# disqus: 

page_gen-dirs: false

page_gen:
  - index_files: false
    data: 'articles'
    template: 'gen-article'
    name: 'ID'
    dir: 'articles'

  - index_files: false
    data: 'articles'
    template: 'gen-bibtex'
    name: 'ID'
    dir: 'bibtex'
    extension: 'bib'

  - index_files: false
    data: 'authors'
    template: 'gen-author'
    name: 'id'
    dir: 'authors'

  - index_files: false
    data: 'keywords'
    template: 'gen-topic'
    name: 'id'
    dir: 'topics'

  - index_files: false
    data: 'journals'
    template: 'gen-journal'
    name: 'id'
    dir: 'journals'
