# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CoV Index
description: > # this means to ignore newlines until next variable
  CoV Index is the map of Coronavirus Science.
license: "cc 2020"

# Links
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://covindex.com" # the base hostname & protocol for your site
permalink: none

# include/exclude files
include: ["_pages", "_root", "_js"]
exclude: ["docs", "Readme.md", "Todo.md", "Makefile", "vendor", "Gemfile", "Gemfile.lock"]

# Build settings
markdown: kramdown

sass:
  style: compressed

plugins:
  - jekyll-sitemap
  - data_page_generator

# Email
# email: iandennismiller@gmail.com

# Twitter
# twitter_username: iandennismiller

# GitHub
# github_username: iandennismiller

# Google Analytics
# google_analytics_id: 

# Disqus comments
# disqus: 

page_gen:
  - index_files: false
    data: 'authors'
    template: 'gen-author'
    name: 'slug'
    dir: 'authors'
  - index_files: false
    data: 'articles'
    template: 'gen-article'
    name: 'ID'
    dir: 'articles'
  - index_files: false
    data: 'articles'
    template: 'gen-bibtex'
    name: 'ID'
    dir: 'bib'
    extension: 'bib'
  - index_files: false
    data: 'keywords'
    template: 'gen-topic'
    name: 'slug'
    dir: 'topics'
